### PR TITLE
feat: support `Iconify` collection packages

### LINKED ISSUE #70: Support Iconify collection packages
https://github.com/iconify/collections-json/issues/15#issuecomment-927016182

### PR DESCRIPTION
**Pull request by userquin**
This PR also includes:
- backward compatibility when `@iconify/json` installed (this dependency is now optional: just added the dependency to `peerDependenciesMeta`)
- update deps: `taze -r -w`
- install `@iconify/json` `dev dependency` on all examples not including it
- add `*-icon-set` variant for each example to use this new feat
- update readme to include the breaking change
- update readme to include `Fully tree shakable` feature

I don't know why `nuxt`, `vue-cli` and `webapack` examples stop working, I'm not able to just run them, so please, check what's happening with these 3 guys.

closes #70

### CODE REVIEW

**Comment by userquin** [comment]
I need to review a few things...

**Comment by userquin** [comment]
We need to take care with the `@iconify/json` package in this repo and future updates. If one of my PR is published on the next branch we can have troubles since will include breaking changes.

 /cc @cyberalien can you add a suffix and so we can differenciate from previous version or just ping me or to @antfu here if released in a future?

**Comment by userquin** [comment]
Since `sveltekit` and `vite-svelte` are using `esm` seems to be not working with `json`, I'm fixing both examples.

**Comment by userquin** [comment]
To run `sveltekit` and `vite-svelte` we need to run it on `node 16` to be able to enable `--experimental-json-modules`, so I'll revert changes to use legacy icons on both examples..

I will check if `cross-env NODE_OPTIONS=--experimental-json-modules npx svelte-kit dev` works on node 16 and then revert changes, maybe we can include some input on readme docs.

**Comment by userquin** [comment]
It is not working on `node 16`: `Dynamic require of "@iconify-json/logos" is not supported`.

To make it working I need to add on `tsup.config.ts` the target option with `target: 'node16'` (defaults to `node12`), and rebuild the modules, then update the `dev` script with:
```shell
# vite-svelte
cross-env NODE_OPTIONS=--experimental-specifier-resolution=node DEBUG=unplugin-icons:* npx vite
# sveltekit
cross-env NODE_OPTIONS=--experimental-specifier-resolution=node npx svelte-kit dev
```

**Comment by cyberalien** [comment]
Is it possible to just read `icons.json` instead of importing it? Then you don't need any flags. Or is it meant to work in both browser and node?

**Comment by userquin** [comment]
> meant

The problem was that Anthony use `try { xxx } catch { ... }` and cannot see the error, then I added a log and the problem was not with loading the `json`, the problem is the target on tsup that defaults to node12 and so all mjs modules will use `cjs require`.

So you don't need to change anything, works really well.

**Comment by userquin** [comment]
To make it working we need at least `node14`, but `vite-vue2` fails: 

```shell
23:28:56 [vite] Internal server error: transpile is not a function
      at Vue2Compiler (F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\dist\chunk-R5DB7RLF.js:206:14)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at async Context.load (F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\dist\chunk-R5DB7RLF.js:386:22)
      at async Object.load (F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:50354:32)
      at async transformRequest (F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:65353:24)
      at async viteTransformMiddleware (F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:65542:32)
```

**Comment by userquin** [comment]
To make `sveltekit` and `vite-svelte` works, we need to change `modern.ts` module to use `createRequire` on `esm` since we're using `"target": "node12"` when building the repo.

The problem is that with `node12` all `mjs` modules will transform the dynamic import for `@iconify-json/${name}` to use `__toModule(__require(name))` and so on esm we don't have `require` (`__require` will check if `require`  is present and will throw an error `Dynamic module cannot be found...` if missing). The problem is not the importing `json` as module from `@iconify-json/${name}` modules.

In fact we don't need to use `dynamic import`, we can use this on `modern.ts` module:
```ts
import { createRequire } from 'module'

const _require = typeof __dirname === 'undefined' ? createRequire(import.meta.url) : require

export async function loadCollection(name: string): Promise<IconifyJSON | undefined> {
  if (_collections[name] === false)
    return undefined

  if (_collections[name])
    return _collections[name] as IconifyJSON

  try {
    debugCollection(`${name}`)
    const { icons } = _require(`@iconify-json/${name}`)
    _collections[name] = icons
    return icons
  }
  catch {
    debugCollection(`failed to load ${name}`)
    _collections[name] = false
    return undefined
  }
}
```

**Comment by userquin** [comment]
can you open a new branch with this PR?

**Pull request merged**
