### PR TITLE
docs: fix vite-react example

### LINKED ISSUE #66: [vite-react] Runtime error in vite-react example
I'm trying to run the vite-react example from the examples folder, but am getting a runtime error.  Here's what I did:

```
cd unplugin-icons
pnpm install
pnpm run build
cd examples/vite-react
pnpm run dev
```

The build completes, but when I open the browser I get this error in the console:

```
Uncaught ReferenceError: React is not defined
    at logosReact (react.jsx:2)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)

The above error occurred in the <logosReact> component:

    at logosReact (http://localhost:3000/@id/~icons/logos/react.jsx:2:3)
    at header
    at div
    at App (http://localhost:3000/src/App.tsx:31:29)

```

### PR DESCRIPTION
**Pull request by IanVS**
Fixes #66.

### CODE REVIEW

**Comment by userquin** [comment]
@IanVS can you add this to the `src/vite-env.d.ts` to fix VSCode, it complains:
/// <reference types="vite/client" />
/// <reference types="unplugin-icons/types/react" />

**Comment by IanVS** [comment]
Hmmm, that's already in the `tsconfig.json`.  And it doesn't look like vscode is complaining for me.  

image

**Comment by userquin** [comment]
see #64, I don't use VSCode but IntellJ cannot resolve the types, just show all `d.ts` available:

imagen

If I add this line then when `crtl + (pressed) mouse click` (goto definition):

imagen

**Comment by IanVS** [comment]
Actually, it seems like adding `jsx: 'react',` shouldn't be necessary.  According to the docs, that's the default.  Are the docs wrong, or maybe the default isn't being applied correctly?

**Comment by IanVS** [comment]
I guess it's not really a hard default.  It tries to guess based on whether or not preact is installed, and since this is a monorepo which also contains preact, I guess `has-pkg` is finding it.

**Comment by userquin** [comment]
It seems the something is failing, adding changes on this PR just works, without it just fails: on linked issue seems also not working without it, so it is not a problem with monorepo (fails on its project).

**Comment by IanVS** [comment]
I'm not sure what you're referring to, @userquin, sorry.  

As for the typescript changes, maybe they can be handled in a separate PR?  They're not really related to the issue I linked to in the description.

**Pull request merged**
